INSERT INTO Category (type, category) VALUES ('Boots', 'Footwear');
INSERT INTO Category (type, category) VALUES ('Sweater', 'Clothes');
INSERT INTO Category (type, category) VALUES ('Scarfs', 'Accesories');
INSERT INTO Category (type, category) VALUES ('Shirts', 'Clothes');
INSERT INTO Category (type, category) VALUES ('Jewelery', 'Accesories');
INSERT INTO Category (type, category) VALUES ('Wallets', 'Accesories');
INSERT INTO Category (type, category) VALUES ('Pants', 'Clothes');
INSERT INTO Category (type, category) VALUES ('Skirts', 'Clothes');
INSERT INTO Category (type, category) VALUES ('Jackets', 'Clothes');
INSERT INTO Category (type, category) VALUES ('Dresses', 'Clothes');
INSERT INTO Category (type, category) VALUES ('Watches', 'Accesories');
INSERT INTO product (UPC_code, type, department, description) VALUES ('48321281308blk', 'Boots', 'Man' ,'Waterpoof lined boots');
INSERT INTO product (UPC_code, type, department, description) VALUES ('48321281309blk', 'Boots', 'Man' ,'Waterpoof lined boots');
INSERT INTO product (UPC_code, type, department, description) VALUES ('48321281310blk', 'Boots', 'Man' ,'Waterpoof lined boots');
INSERT INTO product (UPC_code, type, department, description) VALUES ('48321281311blk', 'Boots', 'Man' ,'Waterpoof lined boots');
INSERT INTO product (UPC_code, type, department, description) VALUES ('48321281312blk', 'Boots', 'Man' ,'Waterpoof lined boots');
INSERT INTO product (UPC_code, type, department, description) VALUES ('48321281313blk', 'Boots', 'Man' ,'Waterpoof lined boots');
INSERT INTO product (UPC_code, type, department, description) VALUES ('48321281308brw', 'Boots', 'Man' ,'Waterpoof lined boots');
INSERT INTO product (UPC_code, type, department, description) VALUES ('48321281309brw', 'Boots', 'Man' ,'Waterpoof lined boots');
INSERT INTO product (UPC_code, type, department, description) VALUES ('48321281310brw', 'Boots', 'Man' ,'Waterpoof lined boots');
INSERT INTO product (UPC_code, type, department, description) VALUES ('48321281311brw', 'Boots', 'Man' ,'Waterpoof lined boots');
INSERT INTO product (UPC_code, type, department, description) VALUES ('48321281312brw', 'Boots', 'Man' ,'Waterpoof lined boots');
INSERT INTO product (UPC_code, type, department, description) VALUES ('48321281313brw', 'Boots', 'Man' ,'Waterpoof lined boots');
INSERT INTO product (UPC_code, type, department, description) VALUES ('11410579805blk', 'Boots', 'Woman' ,'Platform boots');
INSERT INTO product (UPC_code, type, department, description) VALUES ('11410579806blk', 'Boots', 'Woman' ,'Platform boots');
INSERT INTO product (UPC_code, type, department, description) VALUES ('11410579807blk', 'Boots', 'Woman' ,'Platform boots');
INSERT INTO product (UPC_code, type, department, description) VALUES ('11410579808blk', 'Boots', 'Woman' ,'Platform boots');
INSERT INTO product (UPC_code, type, department, description) VALUES ('11410579809blk', 'Boots', 'Woman' ,'Platform boots');
INSERT INTO product (UPC_code, type, department, description) VALUES ('11410579810blk', 'Boots', 'Woman' ,'Platform boots');
INSERT INTO product (UPC_code, type, department, description) VALUES ('11410579811blk', 'Boots', 'Woman' ,'Platform boots');
INSERT INTO product (UPC_code, type, department, description) VALUES ('11410579805brw', 'Boots', 'Woman' ,'Platform boots');
INSERT INTO product (UPC_code, type, department, description) VALUES ('11410579806brw', 'Boots', 'Woman' ,'Platform boots');
INSERT INTO product (UPC_code, type, department, description) VALUES ('11410579807brw', 'Boots', 'Woman' ,'Platform boots');
INSERT INTO product (UPC_code, type, department, description) VALUES ('11410579808brw', 'Boots', 'Woman' ,'Platform boots');
INSERT INTO product (UPC_code, type, department, description) VALUES ('11410579809brw', 'Boots', 'Woman' ,'Platform boots');
INSERT INTO product (UPC_code, type, department, description) VALUES ('11410579810brw', 'Boots', 'Woman' ,'Platform boots');
INSERT INTO product (UPC_code, type, department, description) VALUES ('11410579811brw', 'Boots', 'Woman' ,'Platform boots');
INSERT INTO product (UPC_code, type, department, description) VALUES ('11410579805cam', 'Boots', 'Woman' ,'Platform boots');
INSERT INTO product (UPC_code, type, department, description) VALUES ('11410579806cam', 'Boots', 'Woman' ,'Platform boots');
INSERT INTO product (UPC_code, type, department, description) VALUES ('11410579807cam', 'Boots', 'Woman' ,'Platform boots');
INSERT INTO product (UPC_code, type, department, description) VALUES ('11410579808cam', 'Boots', 'Woman' ,'Platform boots');
INSERT INTO product (UPC_code, type, department, description) VALUES ('11410579809cam', 'Boots', 'Woman' ,'Platform boots');
INSERT INTO product (UPC_code, type, department, description) VALUES ('11410579810cam', 'Boots', 'Woman' ,'Platform boots');
INSERT INTO product (UPC_code, type, department, description) VALUES ('11410579811cam', 'Boots', 'Woman' ,'Platform boots');
INSERT INTO product (UPC_code, type, department, description) VALUES ('88241088001blk', 'Sweater', 'Woman' ,'V neck sweater');
INSERT INTO product (UPC_code, type, department, description) VALUES ('88241088002blk', 'Sweater', 'Woman' ,'V neck sweater');
INSERT INTO product (UPC_code, type, department, description) VALUES ('88241088003blk', 'Sweater', 'Woman' ,'V neck sweater');
INSERT INTO product (UPC_code, type, department, description) VALUES ('88241088001brw', 'Sweater', 'Woman' ,'V neck sweater');
INSERT INTO product (UPC_code, type, department, description) VALUES ('88241088002brw', 'Sweater', 'Woman' ,'V neck sweater');
INSERT INTO product (UPC_code, type, department, description) VALUES ('88241088003brw', 'Sweater', 'Woman' ,'V neck sweater');
INSERT INTO product (UPC_code, type, department, description) VALUES ('88241088001cam', 'Sweater', 'Woman' ,'V neck sweater');
INSERT INTO product (UPC_code, type, department, description) VALUES ('88241088002cam', 'Sweater', 'Woman' ,'V neck sweater');
INSERT INTO product (UPC_code, type, department, description) VALUES ('88241088003cam', 'Sweater', 'Woman' ,'V neck sweater');
INSERT INTO product (UPC_code, type, department, description) VALUES ('65130871400blu', 'Scarfs', 'Woman' ,'Cashmere scarf');
INSERT INTO product (UPC_code, type, department, description) VALUES ('65130871400cam', 'Scarfs', 'Woman' ,'Cashmere scarf');
INSERT INTO product (UPC_code, type, department, description) VALUES ('65130871400pnk', 'Scarfs', 'Woman' ,'Cashmere scarf');
INSERT INTO product (UPC_code, type, department, description) VALUES ('12398397701blu', 'Shirts', 'Man' ,'Dress shirt');
INSERT INTO product (UPC_code, type, department, description) VALUES ('12398397702blu', 'Shirts', 'Man' ,'Dress shirt');
INSERT INTO product (UPC_code, type, department, description) VALUES ('12398397703blu', 'Shirts', 'Man' ,'Dress shirt');
INSERT INTO product (UPC_code, type, department, description) VALUES ('12398397701wht', 'Shirts', 'Man' ,'Dress shirt');
INSERT INTO product (UPC_code, type, department, description) VALUES ('12398397702wht', 'Shirts', 'Man' ,'Dress shirt');
INSERT INTO product (UPC_code, type, department, description) VALUES ('12398397703wht', 'Shirts', 'Man' ,'Dress shirt');
INSERT INTO product (UPC_code, type, department, description) VALUES ('12398397701grn', 'Shirts', 'Man' ,'Dress shirt');
INSERT INTO product (UPC_code, type, department, description) VALUES ('12398397702grn', 'Shirts', 'Man' ,'Dress shirt');
INSERT INTO product (UPC_code, type, department, description) VALUES ('12398397703grn', 'Shirts', 'Man' ,'Dress shirt');
INSERT INTO product (UPC_code, type, department, description) VALUES ('24990892601blu', 'Shirts', 'Woman' ,'Dress shirt');
INSERT INTO product (UPC_code, type, department, description) VALUES ('24990892602blu', 'Shirts', 'Woman' ,'Dress shirt');
INSERT INTO product (UPC_code, type, department, description) VALUES ('24990892603blu', 'Shirts', 'Woman' ,'Dress shirt');
INSERT INTO product (UPC_code, type, department, description) VALUES ('24990892601wht', 'Shirts', 'Woman' ,'Dress shirt');
INSERT INTO product (UPC_code, type, department, description) VALUES ('24990892602wht', 'Shirts', 'Woman' ,'Dress shirt');
INSERT INTO product (UPC_code, type, department, description) VALUES ('24990892603wht', 'Shirts', 'Woman' ,'Dress shirt');
INSERT INTO product (UPC_code, type, department, description) VALUES ('24990892601pnk', 'Shirts', 'Woman' ,'Dress shirt');
INSERT INTO product (UPC_code, type, department, description) VALUES ('24990892602pnk', 'Shirts', 'Woman' ,'Dress shirt');
INSERT INTO product (UPC_code, type, department, description) VALUES ('24990892603pnk', 'Shirts', 'Woman' ,'Dress shirt');
INSERT INTO product (UPC_code, type, department, description) VALUES ('42974873300slv', 'Jewelery', 'Woman' ,'Necklace');
INSERT INTO product (UPC_code, type, department, description) VALUES ('42974873300gld', 'Jewelery', 'Woman' ,'Necklace');
INSERT INTO product (UPC_code, type, department, description) VALUES ('94135319600blk', 'Wallets', 'Man' ,'Leather wallet');
INSERT INTO product (UPC_code, type, department, description) VALUES ('94135319600brw', 'Wallets', 'Man' ,'Leather wallet');
INSERT INTO product (UPC_code, type, department, description) VALUES ('78231376130blk', 'Pants', 'Man' ,'Straight chinos');
INSERT INTO product (UPC_code, type, department, description) VALUES ('78231376132blk', 'Pants', 'Man' ,'Straight chinos');
INSERT INTO product (UPC_code, type, department, description) VALUES ('78231376134blk', 'Pants', 'Man' ,'Straight chinos');
INSERT INTO product (UPC_code, type, department, description) VALUES ('78231376136blk', 'Pants', 'Man' ,'Straight chinos');
INSERT INTO product (UPC_code, type, department, description) VALUES ('78231376130brw', 'Pants', 'Man' ,'Straight chinos');
INSERT INTO product (UPC_code, type, department, description) VALUES ('78231376132brw', 'Pants', 'Man' ,'Straight chinos');
INSERT INTO product (UPC_code, type, department, description) VALUES ('78231376134brw', 'Pants', 'Man' ,'Straight chinos');
INSERT INTO product (UPC_code, type, department, description) VALUES ('78231376136brw', 'Pants', 'Man' ,'Straight chinos');
INSERT INTO product (UPC_code, type, department, description) VALUES ('78231376130cam', 'Pants', 'Man' ,'Straight chinos');
INSERT INTO product (UPC_code, type, department, description) VALUES ('78231376132cam', 'Pants', 'Man' ,'Straight chinos');
INSERT INTO product (UPC_code, type, department, description) VALUES ('78231376134cam', 'Pants', 'Man' ,'Straight chinos');
INSERT INTO product (UPC_code, type, department, description) VALUES ('78231376136cam', 'Pants', 'Man' ,'Straight chinos');
INSERT INTO product (UPC_code, type, department, description) VALUES ('78231376130blu', 'Pants', 'Man' ,'Straight chinos');
INSERT INTO product (UPC_code, type, department, description) VALUES ('78231376132blu', 'Pants', 'Man' ,'Straight chinos');
INSERT INTO product (UPC_code, type, department, description) VALUES ('78231376134blu', 'Pants', 'Man' ,'Straight chinos');
INSERT INTO product (UPC_code, type, department, description) VALUES ('78231376136blu', 'Pants', 'Man' ,'Straight chinos');
INSERT INTO product (UPC_code, type, department, description) VALUES ('90148694002blk', 'Pants', 'Woman' ,'Skinny jeans');
INSERT INTO product (UPC_code, type, department, description) VALUES ('90148694004blk', 'Pants', 'Woman' ,'Skinny jeans');
INSERT INTO product (UPC_code, type, department, description) VALUES ('90148694006blk', 'Pants', 'Woman' ,'Skinny jeans');
INSERT INTO product (UPC_code, type, department, description) VALUES ('90148694008blk', 'Pants', 'Woman' ,'Skinny jeans');
INSERT INTO product (UPC_code, type, department, description) VALUES ('90148694002blu', 'Pants', 'Woman' ,'Skinny jeans');
INSERT INTO product (UPC_code, type, department, description) VALUES ('90148694004blu', 'Pants', 'Woman' ,'Skinny jeans');
INSERT INTO product (UPC_code, type, department, description) VALUES ('90148694006blu', 'Pants', 'Woman' ,'Skinny jeans');
INSERT INTO product (UPC_code, type, department, description) VALUES ('90148694008blu', 'Pants', 'Woman' ,'Skinny jeans');
INSERT INTO product (UPC_code, type, department, description) VALUES ('15495457802blk', 'Skirts', 'Woman' ,'Short skirt');
INSERT INTO product (UPC_code, type, department, description) VALUES ('15495457804blk', 'Skirts', 'Woman' ,'Short skirt');
INSERT INTO product (UPC_code, type, department, description) VALUES ('15495457806blk', 'Skirts', 'Woman' ,'Short skirt');
INSERT INTO product (UPC_code, type, department, description) VALUES ('15495457808blk', 'Skirts', 'Woman' ,'Short skirt');
INSERT INTO product (UPC_code, type, department, description) VALUES ('15495457802blu', 'Skirts', 'Woman' ,'Short skirt');
INSERT INTO product (UPC_code, type, department, description) VALUES ('15495457804blu', 'Skirts', 'Woman' ,'Short skirt');
INSERT INTO product (UPC_code, type, department, description) VALUES ('15495457806blu', 'Skirts', 'Woman' ,'Short skirt');
INSERT INTO product (UPC_code, type, department, description) VALUES ('15495457808blu', 'Skirts', 'Woman' ,'Short skirt');
INSERT INTO product (UPC_code, type, department, description) VALUES ('15495457802yel', 'Skirts', 'Woman' ,'Short skirt');
INSERT INTO product (UPC_code, type, department, description) VALUES ('15495457804yel', 'Skirts', 'Woman' ,'Short skirt');
INSERT INTO product (UPC_code, type, department, description) VALUES ('15495457806yel', 'Skirts', 'Woman' ,'Short skirt');
INSERT INTO product (UPC_code, type, department, description) VALUES ('15495457808yel', 'Skirts', 'Woman' ,'Short skirt');
INSERT INTO product (UPC_code, type, department, description) VALUES ('30192182801blk', 'Jackets', 'Man' ,'Leather jacket');
INSERT INTO product (UPC_code, type, department, description) VALUES ('30192182802blk', 'Jackets', 'Man' ,'Leather jacket');
INSERT INTO product (UPC_code, type, department, description) VALUES ('30192182803blk', 'Jackets', 'Man' ,'Leather jacket');
INSERT INTO product (UPC_code, type, department, description) VALUES ('30192182801brw', 'Jackets', 'Man' ,'Leather jacket');
INSERT INTO product (UPC_code, type, department, description) VALUES ('30192182802brw', 'Jackets', 'Man' ,'Leather jacket');
INSERT INTO product (UPC_code, type, department, description) VALUES ('30192182803brw', 'Jackets', 'Man' ,'Leather jacket');
INSERT INTO product (UPC_code, type, department, description) VALUES ('29747127701grn', 'Dresses', 'Woman' ,'Velvet dress');
INSERT INTO product (UPC_code, type, department, description) VALUES ('29747127702grn', 'Dresses', 'Woman' ,'Velvet dress');
INSERT INTO product (UPC_code, type, department, description) VALUES ('29747127703grn', 'Dresses', 'Woman' ,'Velvet dress');
INSERT INTO product (UPC_code, type, department, description) VALUES ('29747127701pnk', 'Dresses', 'Woman' ,'Velvet dress');
INSERT INTO product (UPC_code, type, department, description) VALUES ('29747127702pnk', 'Dresses', 'Woman' ,'Velvet dress');
INSERT INTO product (UPC_code, type, department, description) VALUES ('29747127703pnk', 'Dresses', 'Woman' ,'Velvet dress');
INSERT INTO product (UPC_code, type, department, description) VALUES ('29747127701yel', 'Dresses', 'Woman' ,'Velvet dress');
INSERT INTO product (UPC_code, type, department, description) VALUES ('29747127702yel', 'Dresses', 'Woman' ,'Velvet dress');
INSERT INTO product (UPC_code, type, department, description) VALUES ('29747127703yel', 'Dresses', 'Woman' ,'Velvet dress');
INSERT INTO product (UPC_code, type, department, description) VALUES ('36020144000slv', 'Watches', 'Man' ,'Metal watch');